"""Declarative base and shared mixins.

Conventions frozen here (TZ 3.3, 3.4, plan decisions D12 and D14):

* primary keys are ``BIGINT GENERATED BY DEFAULT AS IDENTITY`` (D14);
* every timestamp column is ``timestamptz`` and stores UTC (TZ 3.4);
* ``TIME`` columns hold venue-local time and never carry a timezone (D12);
* venue scoping comes from a mixin so that no table silently loses ``venue_id`` (TZ 3.3).
"""

from __future__ import annotations

import datetime as dt
from decimal import Decimal
from typing import Any

from sqlalchemy import BigInteger, DateTime, ForeignKey, Identity, MetaData, Numeric, Text, func
from sqlalchemy.orm import DeclarativeBase, Mapped, MappedColumn, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every table of the project."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {  # noqa: RUF012 - SQLAlchemy declarative directive
        str: Text(),
        dt.datetime: DateTime(timezone=True),
        Decimal: Numeric(),
    }


def fk(
    target: str,
    *,
    ondelete: str = "RESTRICT",
    nullable: bool = False,
    index: bool = False,
) -> MappedColumn[Any]:
    """Shorthand for a BIGINT foreign key column (all primary keys are BIGINT, D14)."""
    return mapped_column(
        BigInteger,
        ForeignKey(target, ondelete=ondelete),
        nullable=nullable,
        index=index,
    )


class IdMixin:
    """BIGINT identity primary key (D14: ids must fit into 64-byte callback_data)."""

    id: Mapped[int] = mapped_column(BigInteger, Identity(always=False), primary_key=True)


class CreatedAtMixin:
    """`created_at` only, for tables that TZ section 4 declares without `updated_at`."""

    created_at: Mapped[dt.datetime] = mapped_column(server_default=func.now(), nullable=False)


class TimestampMixin(CreatedAtMixin):
    """`created_at` + `updated_at`, both timestamptz in UTC."""

    updated_at: Mapped[dt.datetime] = mapped_column(
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class VenueScopedMixin:
    """Mandatory venue scope (TZ 3.3): repositories filter every query by it."""

    venue_id: Mapped[int] = fk("venues.id", ondelete="CASCADE", index=True)


class LibraryScopedMixin:
    """Venue scope that may be NULL — the shared BarPoint library (TZ 3.3).

    Allowed only for `recipes` and `knowledge_articles` (decision D9); the repository
    whitelist in `src/db/repositories/base.py` enforces the same rule at query level.
    """

    venue_id: Mapped[int | None] = fk(
        "venues.id",
        ondelete="CASCADE",
        nullable=True,
        index=True,
    )
